### ISSUE TITLE
Gaphas meta data update and scaling not fully working for group/ungroup/substitute state(s)

### ISSUE THREAD

**Issue by franzlst** [franzlst/issue-mover-test#14]
The issue combines problem with meta data scaling or update when doing a group states, ungroup state or substitute state action. The sub-tasks concern smaller elements to be fixed to improve usability and maybe also features that are not implemented for opengl.

* [x] scaling and relative position changes of group states and ungroup state actions should work simular to opengl
* [ ] suspend drawing meta data for all three actions similar to state type change
* [x] the right usage of the meta_signal of the state model to inform the gaphas viewer about changes made by the model has to be found, too. At the moment, the signal creates problems with the modification history.

Fill free to add some sub-task concerning this three actions. :smile:
